### ISSUE TITLE
 invalid syntax

### ISSUE THREAD

**Issue by Tealk** [ashwinvis/umatrix2ublock#4]
```
python ../umatrix2ublock.py my-umatrix-rules.txt my-ublock-dynamic-rules_2020-02-26_14.07.25.txt
  File "../umatrix2ublock.py", line 65
    ub_rule = f"{src} {dest} {ub_request} {ub_action}"
                                                     ^
SyntaxError: invalid syntax
```

**Comment by Doelli** [comment]
I  can confirm ths issue.

**EDIT:** I found the Bug

Replace Line 65 from:

  ub_rule = **f**"{src} {dest} {ub_request} {ub_action}"

to:
       
 ub_rule = "{src} {dest} {ub_request} {ub_action}"

**Comment by ashwinvis** [comment]
@Tealk @Doelli It is not a bug. f-strings are a feature which requires Python 3.6+
